logger:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler

  datefmt: '%Y-%m-%d %H:%M:%S'

app:
  host: '0.0.0.0'
  port: 8080