---
version: "3.4"
services:
  peterpy:
    container_name: peterpy
    build:
      context: ../peterpy
      dockerfile: Dockerfile
    command: poetry run peterpy
    restart: always
    develop:
      watch:
        - action: sync
          path: ./peterpy
          target: /app/peterpy
        - action: rebuild
          path: config.yaml
    ports:
      - "9096:8080"
    environment:
      - APP_ENV=development
    networks:
      - backend

networks:
  backend:
    driver: bridge
