---
version: "3.4"
# services:
# during development use the vscode debugger to run the app
# peterpy:
#   container_name: peterpy
#   build:
#     context: ../peterpy
#     dockerfile: Dockerfile
#   command: poetry run peterpy
#   restart: always
#   develop:
#     watch:
#       - action: rebuild
#         path: ./peterpy
#         target: /app/peterpy
#       - action: rebuild
#         path: config.yaml
#   ports:
#     - "9090:8080"
#   environment:
#     - APP_ENV=development
#   networks:
#     - backend

networks:
  backend:
    driver: bridge
