---
version: "3.4"
services:
  peterpy:
    container_name: peterpy
    build:
      context: ../peterpy
      dockerfile: Dockerfile
    command: poetry run peterpy
    restart: always
    ports:
      - "9096:8080"
    environment:
      - APP_ENV=development
    networks:
      - backend

networks:
  backend:
    driver: bridge
