---
version: "3.4"
services:
  # during development use the vscode debugger to run the app
  # peterpy:
  #   container_name: peterpy
  #   build:
  #     context: ../peterpy
  #     dockerfile: Dockerfile
  #   command: poetry run peterpy
  #   restart: always
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./peterpy
  #         target: /app/peterpy
  #       - action: rebuild
  #         path: config.yaml
  #   ports:
  #     - "9090:8080"
  #   environment:
  #     - APP_ENV=development
  #   networks:
  #     - backend

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peterpy
      MYSQL_TCP_PORT: 3306
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: peterpy-volume-data
        target: /var/lib/peterpy

networks:
  backend:
    driver: bridge

volumes:
  peterpy-volume-data:
