---
version: "3.4"
services:
  peterpy:
    container_name: peterpy
    build:
      context: ../peterpy
      dockerfile: Dockerfile
    command: poetry run peterpy
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./peterpy
          target: /app/peterpy
        - action: rebuild
          path: config.development.yaml
    ports:
      - "${PETERPY_APP_CONTAINER_PORT}:${PETERPY_APP_PORT}"
    environment:
      - APP_ENV=development
    networks:
      - backend

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PETERPY_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PETERPY_MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${PETERPY_MYSQL_TCP_PORT}
    networks:
      - backend
    ports:
      - ${PETERPY_MYSQL_CONTAINER_PORT}:${PETERPY_MYSQL_TCP_PORT}
    volumes:
      - type: volume
        source: peterpy-volume-data
        target: /var/lib/peterpy

networks:
  backend:
    driver: bridge

volumes:
  peterpy-volume-data:
